Repository shibayan/keyvault-acmebot, pull requests merged in 2020-08, with the labels that each got.

#138 Change to only renew certificates issued to the same endpoint
  KeyVault.Acmebot/SharedFunctions.cs
Labels: enhancement

#139 Update Deploy to Azure Button
  README.md
  README_ja.md
Labels: documentation

#142 Update README.md
  README.md
  README_ja.md
Labels: documentation

#143 Update certificate tags filtering
  .gitignore
  KeyVault.Acmebot/Internal/CertificateItemExtensions.cs
  KeyVault.Acmebot/Internal/WebhookClient.cs
  KeyVault.Acmebot/SharedFunctions.cs
Labels: bug

#144 Adding support to Azure Government and China
  KeyVault.Acmebot/Internal/AppAuthenticationTokenProvider.cs
  KeyVault.Acmebot/Internal/AzureEnvironment.cs
  KeyVault.Acmebot/Options/AcmebotOptions.cs
  KeyVault.Acmebot/Providers/AzureDnsProvider.cs
  KeyVault.Acmebot/Startup.cs
  README.md
  azuredeploy.json
Labels: enhancement

#146 Update to readme with more configuration, update and delete instructions
  README.md
Labels: documentation

#148 Update DurableTask v2.3.0
  KeyVault.Acmebot/KeyVault.Acmebot.csproj
Labels: enhancement

#150 Update Durable Task Proxy
  KeyVault.Acmebot/KeyVault.Acmebot.csproj
Labels: bug
