Repository shibayan/keyvault-acmebot, pull requests merged in 2024-04, with the labels that each got.

#691 Handle cases where an authorization is immediately valid
  KeyVault.Acmebot/Functions/SharedActivity.cs
Labels: bug

#698 Update to latest bicep version
  .github/workflows/build.yml
  .github/workflows/publish.yml
  azuredeploy.json
Labels: enhancement

#701 Update bicep version
  .github/workflows/build.yml
  .github/workflows/publish.yml
  azuredeploy.bicep
  azuredeploy.json
Labels: enhancement

#702 Update NuGet packages
  KeyVault.Acmebot/KeyVault.Acmebot.csproj
Labels: dependencies
